version: 2

_default: &default
  docker:
    - image: circleci/node:latest
  working_directory: ~/repo

jobs:
  lint-md:
    <<: *default
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Lint Markdown files
          command: |
            yarn run lint-md
      - run:
          name: Try to build site
          command: |
            yarn run vuepress build
  extended-lint-md:
    <<: *default
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Lint Markdown files
          command: |
            yarn run extended-lint-md
workflows:
  version: 2
  commit:
    jobs:
      - lint-md
  cron:
    triggers:
      - schedule:
          cron: "20 1 * * 1"
          filters:
            branches:
              only:
                - master
    jobs:
      - extended-lint-md
