backend:
  name: git-gateway
  branch: master

media_folder: "images"
public_folder: "/images"

collections:
  - name: "doc"
    label: "Doc"
    folder: "."
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
